### ISSUE TITLE
CHROME_PATH must be set

### ISSUE THREAD

**Issue by stefanwalther** [qlik-oss/after-work.js#139]
### Description

I am trying to follow the requirejs examples.

### Steps to Reproduce

I am running the following command, which works nice locally, but not in CircleCI:

```
 "test:unit": "./node_modules/.bin/aw chrome --url test/unit/index.html --glob test/unit/*.spec.js",
```
I am getting the following
```
Promise Rejection:Error: The environment variable CHROME_PATH must be set to executable of a build of Chromium version 54.0 or later.
Success!
```
I have installed the following as devDependencies for the tests:

```
"devDependencies": {
    "after-work.js": "^4.0.1",
    "protractor": "^5.2.2",
    "webdriver-manager": "^12.0.6"
  },
```

Any ideas what I can do/doing wrong?

##### Operating system
```
[ ] Windows
[x] OSX
[ ] Linux
```
### Versions

* Node.js: v8.9.4
* Webdriver: N/A, but 
* Operating system: OSX resp. Linux (CircleCI)

**Comment by stefanwalther** [comment]
OK, got it, solved it myself:

- Protactor not even needed

Had to declare a different image containing the browser on CircleCI:

```
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install-dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run unit tests
          command: npm run test:unit
```
